services:
  app:
    image: oven/bun:latest
    working_dir: /project
    tty: true
    volumes: 
      - ./my-app:/project 
    command: bun dev
    ports:
      - 3000:3000
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_db
    command: ["postgres", "-p", "5342"]
    ports:
      - "5433:5342"